### ISSUE TITLE
프로젝트 디렉토리명 다름

### ISSUE THREAD

**Issue by mytv100** [mytv100/Eris_Project#13]
Eris-frontend-project
Eris_backend_project

프론트는 하이픈이고
백앤드는 언더바입니다.

프로젝트 디렉토리명이므로 언더바로 하는게 맞겠죠?

**Comment by KimSoungRyoul** [comment]
[https://bearskin.tistory.com/1](https://bearskin.tistory.com/1)

아  앵귤러 프로젝트에서는 네이밍 컨벤션이 케밥케이스 입니다 

저도 정확하게 공식문서는 안봤는데 케밥 케이스를 쓰더라고요 

장고에서는 스네이크 
앵귤러에서는 언더바

쓰는거 강조하고싶어서 그냥 최초 프로젝트를 저렇게 드린겁니다 

자유롭게 수정하셔도 됩니다 

다만 파이참에서도 앵귤러 프로젝트 디렉토리 명 Refactoring을 지원해주는지 모르겠네요 
단순히 폴더 이름만 바꾸면 안돌아가는 경우가 좀 있어서요
바꿔서 프로젝트이름 컨벤션 통일하면 좋지만 

한번 해보고 안되면 그대로 유지해도 컨벤션에는 문제 없을듯 합니다

**Comment by KimSoungRyoul** [comment]
옆에 Labels 이랑 Assignees 도 항상 채워주세요

**Comment by KimSoungRyoul** [comment]
그리고 넵 같은거 대신에 옆에 스마일 버튼 누르는걸로 대체 가능합니다

**Comment by mytv100** [comment]
네 알겠습니다 감사합니다
