### ISSUE TITLE
[Question] what is schema_view in configuration.urls

### ISSUE THREAD

**Issue by mytv100** [mytv100/Eris_Project#14]
1. Eris_backend_project/configuration/urls.py 에서
schema_view 는 무엇이고 
그 내용에 description은 이 project에 대한 설명을 쓰면 되는건가요?

2. 학교에서 리눅스는 인터넷을 쓸 수 없나요? ㅠㅠ
학교에서 하고 집에와서 github에 올려야겠네

**Comment by KimSoungRyoul** [comment]
Schema_view는  Swagger위에  보여지는 내용들입니다 
거기에 님 마음대로 내용 수정해서 쓰시면 
swagger문서에 변경된 것을 볼 수 있을겁니다
