### ISSUE TITLE
[Question] App VS Module

### ISSUE THREAD

**Issue by mytv100** [mytv100/Eris_Project#22]
API 쪽(movie_recommendation) 이랑 Filtering 쪽(movie_filtering - 추천 알고리즘)
이렇게 두 기능인데,

Filtering을 App으로 하나 더 만드는것
                        v s
Filtering.py 형태로 만들어서 사용하는것

어떤게 좋을까요?
App으로 하는게 좋을 것 같긴한데...
공부하는 건

**Comment by KimSoungRyoul** [comment]
추천, 필터링 
 이 두개는 프로젝트 안에서 동사로  쓰이는거 같은데
앱은 도메인이여야되 (영화  회원...etc)
도메인은 대체로 명사 형태인 경우가 많죠
아닌경우도 많지만

후자에 한표 던집니다

**Comment by mytv100** [comment]
1 project 1 app 괜찮습니까? 
app으로 만들기는 애매하긴 했음

**Comment by KimSoungRyoul** [comment]
너무 작다고 걱정하지마 하다보면 자연스레 늘어
