### ISSUE TITLE
[Question] what is http status code about redundancy in ViewSet class 

### ISSUE THREAD

**Issue by mytv100** [mytv100/Eris_Project#23]
ViewSet 클래스에서 create  method에서 request로 들어온 데이터들이 DB에 있으면
202 반환하게 해놨는데
중복 데이터 있는 경우에 대해서는 몇 번 코드를 반환해야 할까요?
상태코드가 굉장히 많네요

**Comment by KimSoungRyoul** [comment]
너가 정하기 나름이야
이미 있는 데이터를 만드려했으니까 
잘못된 요청이니 400 badrequest

**Comment by KimSoungRyoul** [comment]
아니면 request포맷이 틀린건 아니니까
200을 던지되 message로 이미 존재하는데이터라고 
넘겨줄수도 있지

**Comment by KimSoungRyoul** [comment]
Status보니까 202가 가장 정확하긴 하겠다

근데 실무에서는 그런 정보 정확하게주면 해킹빌미를 제공할수있어서 전부 200  400두개로만 통일하기도 하더라

**Comment by mytv100** [comment]
일단 400넘겨주는 걸로 해야겠네 
근데 이거 실시간이네 
새로고침안해도 보이는구나

**Comment by mytv100** [comment]
아래 이슈 하나 더있어요 그것도 좀 봐주세요

**Comment by KimSoungRyoul** [comment]
채팅 가능 개꿀 카톡 안써도됨

**Comment by mytv100** [comment]
아니 나 push 도 실패하고 PR도 실패했는데 깃허브에 올라와있냐 이거 ㅋㅋㅋㅋ
